### ISSUE TITLE
xbox gamepad mapped differently in firefox and chrome on Linux

### ISSUE THREAD

**Issue by qlambert-pro** [w3c/gamepad#133]
I am having issues with my gamepad, its mapping is not consistent across browser.
Chrome detects it as a gamepad with 17 buttons and 4 axes and Firefox as one with 11 buttons and 8 axes.

One other and rather unfortunate difference is that the button which represents the start button in Chrome represents the left analog click in Firefox.

Is this expected or a known issue? Is there something I can do to further investigate or fix the problem.

**Comment by mrmcpowned** [comment]
This repository is more for the actual specification of the API (how it should work, what kind of information is exposed, best practices, etc.) rather than the implementation.

From a technical standpoint, the mappings should be following what's listed under [the spec](https://www.w3.org/TR/gamepad/). If the inputs aren't mapped to what's shown, then it's an issue with the browser vendor.

The problem you're having would be better posting in the bug trackers for the respective browser vendors. I've linked them below for convenience:
**Current Gamepad API bugs in Chromium** - https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%3EGamepadAPI&can=2
**Current Gamepad API bugs in Firefox (under the 'Device Interfaces' category)** - https://bugzilla.mozilla.org/buglist.cgi?product=Core&component=DOM%3A%20Device%20Interfaces&bug_status=__open__

@marcoscaceres Would it be possible to close this?

**Comment by qlambert-pro** [comment]
Yes, thanks for the pointers
